version: '3.6'

networks:
  go-proxy-net:
    name: go-proxy-network

services:
  go-proxy:
    image: nicpearson/gogo-cors-proxy:1.0
    container_name: go-proxy
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - go-proxy-net
    ports:
      - 8181:8181
    command: ["/usr/local/bin/proxy", "-target=docker.for.mac.localhost:8080", "-listen=0.0.0.0:8181", "-host=localhost:3000", "-origin=http://localhost:3000"]
